#!/bin/sh
echo "test2: ./proj3 silent ls -al files"
rm -f out1 

shell_in="silent ls -al files"

#../proj3 silent ls -al files/a* > out1 2>&1  
../proj3 $shell_in > out1 2>&1 

./proj3-ref $shell_in > r2-1 2>&1

diff out1 r2-1

ret_val=$?
exit_val=0;

echo -n "test2 "
if [ $ret_val -ne 0 ]
then
  echo Failed

  echo""
  echo "Correct Output:"
  cat r2-1
  echo ""
  echo "Actual Output:"
  cat out1
  echo ""

  exit_val=1
else
  echo OK
fi

rm -f out1 r2-1
exit $exit_val