#!/bin/sh

echo "test9: ./proj3 silent ls files PIPE grep a"
rm -f out1 

../proj3 silent ls files PIPE grep a > out1 2>&1  

diff out1 r9
ret_val=$?

exit_val=0;

echo -n "test9 "
if [ $ret_val -ne 0 ]
then
  echo Failed

  echo""
  echo "Correct Output:"
  cat r9
  echo ""
  echo "Actual Output:"
  cat out1
  echo ""

  exit_val=1

else
  echo OK
fi

rm -f out1 output
exit $exit_val