#!/bin/sh
echo "test4: ./proj3 silent cat LT files/aaa"
rm -f out1 

../proj3 silent cat LT files/aaa > out1 2>&1  

diff out1 r4
ret_val=$?

exit_val=0;

echo -n "test4 "
if [ $ret_val -ne 0 ]
then
  echo Failed

  echo""
  echo "Correct Output:"
  cat r4
  echo ""
  echo "Actual Output:"
  cat out1
  echo ""

  exit_val=1

else
  echo OK
fi

rm -f out1
exit $exit_val